title: JSEN
sitename: Validate your JSON objects using JSON Schema
keywords: JSON, schema, validator, node, browser, speed, dynamic, code, generation
description: >
  JSEN (JSON Sentinel) validates JSON objects using JSON Schema. Uses dynamic
  code generation to produce high-performance functions that V8 and other
  JavaScript engines can optimize. <b>Works both in node and the browser</b>.
safe: true
repo_url: https://github.com/bugventure/jsen
url: 'http://bugventure.github.io/jsen'
markdown: kramdown
kramdown:
  parse_block_html: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
collections:
  docs:
    output: true
    permalink: /:path
